import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '../../environments/environment';

export interface Child {
  id?: number; // Optional - auto-generated by database
  user_id?: number;
  child_name: string;
  child_last_name?: string;
  childs_formal_name?: string;
  mothers_full_name?: string;
  fathers_full_name?: string;
  child_gender: number;
  height?: number;
  weight?: number;
  child_born_date?: number;
  child_born_month?: number;
  child_born_year?: number;
  profile_Image?: string;
  service_provider_id?: number;
  school_id?: number; // From bmc6_assessment_childs (always 9999)
  student_ref_Id?: string; // Auto-generated if not provided
  school_connect_status?: 'INVITED' | 'ACCEPTED' | 'CONNECTED' | 'REJECTEDBYPARENT' | 'REJECTEDBYTEACHER';
  standard?: string;
  division?: string;
  is_special_child?: number;
  created_on?: string;
  updated_on?: string;
  photo_count?: number;
  video_count?: number;
  class_id?: number; // From config_student
  school_status?: string; // From config_student
}

export interface CreateChildRequest {
  child_name: string;
  child_gender: number;
  school_id: number; // Required for config_student
  class_id: number; // Required for config_student
  child_last_name?: string;
  childs_formal_name?: string;
  mothers_full_name?: string;
  fathers_full_name?: string;
  height?: number;
  weight?: number;
  child_born_date?: number;
  child_born_month?: number;
  child_born_year?: number;
  profile_Image?: string;
  standard?: string;
  division?: string;
}

export interface ChildrenResponse {
  success: boolean;
  total: number;
  count: number;
  children: Child[];
}

export interface ChildFilters {
  page?: number;
  limit?: number;
  school_id?: number;
  standard?: string;
  division?: string;
  service_provider_id?: number;
  search?: string;
  has_media?: boolean;
}

@Injectable({
  providedIn: 'root'
})
export class ChildService {
  private baseUrl = environment.apiUrl;

  constructor(private http: HttpClient) {}

  /**
   * Get all children with optional filters
   */
  getChildren(filters?: ChildFilters): Observable<ChildrenResponse> {
    let params = new HttpParams();

    if (filters) {
      if (filters.page) params = params.set('page', filters.page.toString());
      if (filters.limit) params = params.set('limit', filters.limit.toString());
      if (filters.school_id) params = params.set('school_id', filters.school_id.toString());
      if (filters.standard) params = params.set('standard', filters.standard);
      if (filters.division) params = params.set('division', filters.division);
      if (filters.service_provider_id) params = params.set('service_provider_id', filters.service_provider_id.toString());
      if (filters.search) params = params.set('search', filters.search);
      if (filters.has_media !== undefined) params = params.set('has_media', filters.has_media.toString());
    }

    return this.http.get<ChildrenResponse>(`${this.baseUrl}/children`, { params });
  }

  /**
   * Get child by ID
   */
  getChildById(id: number): Observable<Child> {
    return this.http.get<Child>(`${this.baseUrl}/children/${id}`);
  }

  /**
   * Get child by student reference ID
   */
  getChildByStudentRefId(studentRefId: string): Observable<Child> {
    return this.http.get<Child>(`${this.baseUrl}/children/student/${studentRefId}`);
  }

  /**
   * Create new child (child_id is auto-generated)
   */
  createChild(child: CreateChildRequest): Observable<{ success: boolean; message: string; child: Child; config: any }> {
    return this.http.post<{ success: boolean; message: string; child: Child; config: any }>(
      `${this.baseUrl}/children`,
      child
    );
  }

  /**
   * Update child
   */
  updateChild(id: number, child: Partial<Child>): Observable<{ success: boolean; message: string; child: Child }> {
    return this.http.put<{ success: boolean; message: string; child: Child }>(
      `${this.baseUrl}/children/${id}`,
      child
    );
  }

  /**
   * Delete child
   */
  deleteChild(id: number): Observable<{ success: boolean; message: string }> {
    return this.http.delete<{ success: boolean; message: string }>(
      `${this.baseUrl}/children/${id}`
    );
  }

  /**
   * Get full name of child
   */
  getFullName(child: Child): string {
    return `${child.child_name} ${child.child_last_name}`.trim();
  }

  /**
   * Get age from birth date
   */
  getAge(child: Child): number {
    if (!child.child_born_year || !child.child_born_month || !child.child_born_date) {
      return 0;
    }

    const birthDate = new Date(child.child_born_year, child.child_born_month - 1, child.child_born_date);
    const today = new Date();
    let age = today.getFullYear() - birthDate.getFullYear();
    const monthDiff = today.getMonth() - birthDate.getMonth();
    
    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
      age--;
    }
    
    return age;
  }

  /**
   * Format birth date
   */
  getBirthDate(child: Child): string {
    if (!child.child_born_year || !child.child_born_month || !child.child_born_date) {
      return 'N/A';
    }
    return `${child.child_born_date}/${child.child_born_month}/${child.child_born_year}`;
  }
}
